name: product_hunt
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_lazy_indexed_stack: ^0.0.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  graphql: ^5.1.3
  http: ^0.13.5
  intl: ^0.17.0
  random_avatar: ^0.0.8
  random_name_generator: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  sizer: ^2.0.15
  stream_transform: ^2.1.0
  styled_widget: ^0.4.1
  timeago: ^3.3.0
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
