name: product_hunt

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.6'
      - run: flutter pub get
      - run: flutter test --coverage
